### ISSUE TITLE
diags fail on kitware bot

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcdat-testdata#90]
@danlipsa looking at kitware ctest results i see:

```
writing png file1 /tmp/tmpV1y6JC//figure-set6_Global_ANN_dv_TAUY_ANN_ft0_cam35_data_smaller_plot-0.png for dv_TAUY_ANN_ft0_cam35_data_smaller
Traceback (most recent call last):
  File "/home/buildbot/buildbot/uvcdat-garant-linux-release/build/install/bin/diags", line 589, in <module>
    run_diagnostics_from_options(o)
  File "/home/buildbot/buildbot/uvcdat-garant-linux-release/build/install/bin/diags", line 96, in run_diagnostics_from_options
    run_diagnostics_from_filetables( opts, modelfts, obsfts )
  File "/home/buildbot/buildbot/uvcdat-garant-linux-release/build/install/bin/diags", line 534, in run_diagnostics_from_filetables
    vcanvas.png( fname, ignore_alpha=True, metadata=provenance_dict() )
  File "/home/buildbot/buildbot/uvcdat-garant-linux-release/build/install/lib/python2.7/site-packages/metrics/common/utilities.py", line 117, in provenance_dict
    os.getlogin(), os.getcwd(), " ".join(sys.argv)
OSError: [Errno 25] Inappropriate ioctl for device
```
Could it be VTKpng writer?

**Comment by doutriaux1** [comment]
see: https://open.cdash.org/testDetails.php?test=396955594&build=4126205

**Comment by jbeezley** [comment]
I think this PR will fix the issue: https://github.com/UV-CDAT/uvcmetrics/pull/132.
